name: build dslinter

# Build on every branch every push and pull request change.
on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build and test dslinter's Python source code
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run tests
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml --cov-fail-under=80         

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage.xml
          fail_ci_if_error: true

      - name: Run pylint on dslinter source code
        run: pylint dslinter --fail-under=8
 