name: build dslinter

# Build on every branch every push and pull request change.
on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build and test dslinter's Python source code
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run tests
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage.xml
          fail_ci_if_error: true
        # with:
        #   directory: ./coverage/reports/
        #   env_vars: OS,PYTHON
        #   fail_ci_if_error: true
          # files: ./coverage1.xml,./coverage2.xml
          # flags: unittests
          # name: codecov-umbrella
          # path_to_write_report: ./coverage/codecov_report.txt

      # - name: Run tests
      #   uses: dima-engineer/pytest-reporter@v1.1.3
      #   with:
      #     cov-omit-list: tests/*
      #     cov-threshold-single: 85
      #     cov-threshold-total: 90        

      # - name: Run pylint on dslinter source code
      #   run: pylint dslinter
